/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystem.professor_gui;

/**
 *
 * @author User
 */
public class subjNotes extends javax.swing.JFrame {

    /**
     * Creates new form subjNotes
     */
    public subjNotes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subjectName = new javax.swing.JLabel();
        editSubjButton = new javax.swing.JButton();
        deleteSubjButton = new javax.swing.JButton();
        sessionButton = new javax.swing.JButton();
        noteButton = new javax.swing.JButton();
        studentsButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        notesTable = new javax.swing.JTable();
        addNoteButton = new javax.swing.JButton();
        editNoteButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        subjectName.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        subjectName.setText("Subject Name");

        editSubjButton.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        editSubjButton.setText("Edit Subject");
        editSubjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSubjButtonActionPerformed(evt);
            }
        });

        deleteSubjButton.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        deleteSubjButton.setText("Delete Subject");
        deleteSubjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteSubjButtonActionPerformed(evt);
            }
        });

        sessionButton.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        sessionButton.setText("Sessions");
        sessionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sessionButtonActionPerformed(evt);
            }
        });

        noteButton.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        noteButton.setText("Notes");

        studentsButton.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        studentsButton.setText("Students");
        studentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentsButtonActionPerformed(evt);
            }
        });

        notesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Note Title", "Date Posted"
            }
        ));
        jScrollPane1.setViewportView(notesTable);

        addNoteButton.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        addNoteButton.setText("Add Note");
        addNoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNoteButtonActionPerformed(evt);
            }
        });

        editNoteButton.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        editNoteButton.setText("Edit");
        editNoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editNoteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sessionButton)
                        .addGap(28, 28, 28)
                        .addComponent(noteButton)
                        .addGap(32, 32, 32)
                        .addComponent(studentsButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addNoteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editNoteButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(subjectName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editSubjButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteSubjButton)))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editSubjButton)
                        .addComponent(deleteSubjButton))
                    .addComponent(subjectName))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sessionButton)
                    .addComponent(noteButton)
                    .addComponent(studentsButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addNoteButton)
                    .addComponent(editNoteButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editSubjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSubjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editSubjButtonActionPerformed

    private void deleteSubjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteSubjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteSubjButtonActionPerformed

    private void sessionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sessionButtonActionPerformed
        subjectWindow session = new subjectWindow();
        session.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sessionButtonActionPerformed

    private void studentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentsButtonActionPerformed
       subjStudents students = new subjStudents();
       students.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_studentsButtonActionPerformed

    private void addNoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNoteButtonActionPerformed
        addNote add = new addNote();
        add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addNoteButtonActionPerformed

    private void editNoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editNoteButtonActionPerformed
        editNote edit = new editNote();
        edit.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editNoteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(subjNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(subjNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(subjNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(subjNotes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new subjNotes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNoteButton;
    private javax.swing.JButton deleteSubjButton;
    private javax.swing.JButton editNoteButton;
    private javax.swing.JButton editSubjButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton noteButton;
    private javax.swing.JTable notesTable;
    private javax.swing.JButton sessionButton;
    private javax.swing.JButton studentsButton;
    private javax.swing.JLabel subjectName;
    // End of variables declaration//GEN-END:variables
}
