/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystem.common_gui;

import schoolmanagementsystem.Subject;
import schoolmanagementsystem.Professor;
import javax.swing.JOptionPane;

/**
 *
 * @author nedpals
 */
public class SubjectEditor extends javax.swing.JFrame {
    private Subject sub;
    private Professor[] professors;

    /**
     * Creates new form AdminEditor
     */
    public SubjectEditor() {
        loadDefaults();
    }
    
    public SubjectEditor(String profName) {
        loadDefaults();
        professorSelector.setSelectedItem(profName);
        professorSelector.setEnabled(false);
    }
    
    public SubjectEditor(Subject sub) {
        loadDefaults();
        this.sub = sub;
    }
    
    public SubjectEditor(Subject sub, String profName) {
        loadDefaults();
        this.sub = sub;
        professorSelector.setSelectedItem(profName);
        professorSelector.setEnabled(false);
    }
    
    void loadDefaults() {
        initComponents();
        loadProfessors();
        
        if (sub != null) {
            this.nameField.setText(sub.name);
            this.descriptionField.setText(sub.description);
            this.unitsField.setText(String.valueOf(sub.units));
        }
    }
    
    void loadProfessors() {
        try {
            this.professors = Professor.getAll();
            this.professorSelector.removeAllItems();
            
            for (int i = 0; i < this.professors.length; i++) {
                this.professorSelector.addItem(this.professors[i].name);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            this.professorSelector.setEnabled(false);
            this.dispose();
            //this.professors = new Professor[0];
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        unitsField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        descriptionField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        professorSelector = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Student Editor");

        jLabel2.setText("Name");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Units");

        jLabel6.setText("Description");

        jLabel7.setText("Professor");

        professorSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        professorSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                professorSelectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descriptionField)
                            .addComponent(unitsField)
                            .addComponent(nameField)
                            .addComponent(professorSelector, 0, 224, Short.MAX_VALUE))))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(unitsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(professorSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            Professor selectedProf = this.professors[this.professorSelector.getSelectedIndex()];
            
            if (this.sub == null) {
                this.sub = new Subject(
                        this.nameField.getText(),
                        Integer.valueOf(this.unitsField.getText()),
                        selectedProf.id,
                        this.descriptionField.getText()
                );
                
                selectedProf.createSubject(this.sub);
            } else {
                this.sub.name = this.nameField.getText();
                this.sub.description = this.descriptionField.getText();
                this.sub.units = Integer.valueOf(this.unitsField.getText());
                this.sub.professorId = selectedProf.id;
                this.sub.save();
            }
            
            JOptionPane.showMessageDialog(rootPane, "Subject saved successfully.");
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void professorSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_professorSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_professorSelectorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField descriptionField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameField;
    private javax.swing.JComboBox<String> professorSelector;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField unitsField;
    // End of variables declaration//GEN-END:variables
}
