/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystem.student_gui;

import javax.swing.JOptionPane;
import schoolmanagementsystem.Attendance;
import schoolmanagementsystem.Session;
import schoolmanagementsystem.Subject;
import schoolmanagementsystem.Student;

/**
 *
 * @author nedpals
 */
public class StudentSessionView extends javax.swing.JFrame {
    Session session;
    Student student;
    
    /**
     * Creates new form StudentSessionView
     */
    public StudentSessionView(Session session, Subject subject, Student student) {
        initComponents();
        this.session = session;
        this.student = student;
        
        this.subName.setText(subject.name);
        this.sessionTitle.setText(session.title);
        this.sessionContent.setText(session.description);
        
        try {
            Attendance att = session.getAttendanceFromStudent(student.id);
            presentBtn.setEnabled(att == null || !att.isPresent);
            notPresentBtn.setEnabled(att == null || att.isPresent);
        } catch (Exception e) {
            e.printStackTrace();
            presentBtn.setEnabled(false);
            notPresentBtn.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subName = new javax.swing.JLabel();
        sessionTitle = new javax.swing.JLabel();
        sessionContent = new javax.swing.JLabel();
        notPresentBtn = new javax.swing.JButton();
        presentBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        subName.setText("jLabel1");

        sessionTitle.setFont(sessionTitle.getFont().deriveFont(sessionTitle.getFont().getSize()+10f));
        sessionTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        sessionTitle.setText("jLabel1");

        sessionContent.setText("jLabel1");

        notPresentBtn.setText("Not Present");
        notPresentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notPresentBtnActionPerformed(evt);
            }
        });

        presentBtn.setText("Present");
        presentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sessionContent)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(sessionTitle)
                                .addComponent(subName, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(218, Short.MAX_VALUE)
                        .addComponent(presentBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(notPresentBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(subName)
                .addGap(40, 40, 40)
                .addComponent(sessionTitle)
                .addGap(27, 27, 27)
                .addComponent(sessionContent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 293, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notPresentBtn)
                    .addComponent(presentBtn))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void presentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presentBtnActionPerformed
        try {
            this.student.present(session);
            JOptionPane.showMessageDialog(rootPane, "Attendance recorded successfully.");
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_presentBtnActionPerformed

    private void notPresentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notPresentBtnActionPerformed
        String reason = JOptionPane.showInputDialog(rootPane, "Why are you not present?");
        try {
            if (reason != null && reason.length() != 0) {
                this.student.notPresent(session, reason);
                JOptionPane.showMessageDialog(rootPane, "Attendance recorded successfully.");
                this.dispose();
            } else {
                throw new Exception("Unable to record your attendance.");
            }  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_notPresentBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton notPresentBtn;
    private javax.swing.JButton presentBtn;
    private javax.swing.JLabel sessionContent;
    private javax.swing.JLabel sessionTitle;
    private javax.swing.JLabel subName;
    // End of variables declaration//GEN-END:variables
}
