/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystem.student_gui;

import javax.swing.JOptionPane;
import schoolmanagementsystem.Note;
import schoolmanagementsystem.Subject;
import schoolmanagementsystem.Student;

/**
 *
 * @author nedpals
 */
public class StudentNoteView extends javax.swing.JFrame {
    Note note;
    Student student;
    
    /**
     * Creates new form StudentSessionView
     */
    public StudentNoteView(Note note, Subject subject) {
        initComponents();
        this.note = note;
        
        this.subName.setText(subject.name);
        this.noteTitle.setText(note.title);
        this.noteContent.setText(note.content);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subName = new javax.swing.JLabel();
        noteTitle = new javax.swing.JLabel();
        noteContent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        subName.setText("jLabel1");

        noteTitle.setFont(noteTitle.getFont().deriveFont(noteTitle.getFont().getSize()+10f));
        noteTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        noteTitle.setText("jLabel1");

        noteContent.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noteContent)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(noteTitle)
                        .addComponent(subName, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(subName)
                .addGap(40, 40, 40)
                .addComponent(noteTitle)
                .addGap(27, 27, 27)
                .addComponent(noteContent)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel noteContent;
    private javax.swing.JLabel noteTitle;
    private javax.swing.JLabel subName;
    // End of variables declaration//GEN-END:variables
}
