/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystem.student_gui;
import java.util.Iterator;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import schoolmanagementsystem.student_gui.SubView;
import schoolmanagementsystem.student_gui.NotesView;
/**
 *
 * @author japz3
 */
public class student_win extends javax.swing.JFrame {

    /**
     * Creates new form student
     */
    public student_win() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stud_welcomeLabel = new javax.swing.JLabel();
        stud_todayLabel = new javax.swing.JLabel();
        subj_label = new javax.swing.JLabel();
        stud_subPanel2 = new javax.swing.JPanel();
        stud_subName2 = new javax.swing.JLabel();
        stud_profName2 = new javax.swing.JLabel();
        stud_subEnter2 = new javax.swing.JButton();
        stud_subPanel = new javax.swing.JPanel();
        stud_subName = new javax.swing.JLabel();
        stud_profName = new javax.swing.JLabel();
        stud_subEnter = new javax.swing.JButton();
        stud_subPanel3 = new javax.swing.JPanel();
        stud_subName3 = new javax.swing.JLabel();
        stud_profName3 = new javax.swing.JLabel();
        stud_subEnter3 = new javax.swing.JButton();
        stud_subPanel4 = new javax.swing.JPanel();
        stud_subName4 = new javax.swing.JLabel();
        stud_profName4 = new javax.swing.JLabel();
        stud_subEnter4 = new javax.swing.JButton();
        stud_subPanel5 = new javax.swing.JPanel();
        stud_subName5 = new javax.swing.JLabel();
        stud_profName5 = new javax.swing.JLabel();
        stud_subEnter5 = new javax.swing.JButton();
        stud_subPanel6 = new javax.swing.JPanel();
        stud_subName6 = new javax.swing.JLabel();
        stud_profName6 = new javax.swing.JLabel();
        stud_subEnter6 = new javax.swing.JButton();
        stud_fname = new javax.swing.JLabel();
        stud_date = new javax.swing.JLabel();
        stud_subPanel7 = new javax.swing.JPanel();
        stud_subName7 = new javax.swing.JLabel();
        stud_profName7 = new javax.swing.JLabel();
        stud_subEnter7 = new javax.swing.JButton();
        stud_subPanel8 = new javax.swing.JPanel();
        stud_subName8 = new javax.swing.JLabel();
        stud_profName8 = new javax.swing.JLabel();
        stud_subEnter8 = new javax.swing.JButton();
        stud_subPanel10 = new javax.swing.JPanel();
        stud_subName10 = new javax.swing.JLabel();
        stud_profName10 = new javax.swing.JLabel();
        stud_subEnter10 = new javax.swing.JButton();
        stud_subPanel11 = new javax.swing.JPanel();
        stud_subName11 = new javax.swing.JLabel();
        stud_profName11 = new javax.swing.JLabel();
        stud_subEnter11 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        stud_file_menu = new javax.swing.JMenu();
        stud_versMenu = new javax.swing.JMenuItem();
        stud_exitMenu = new javax.swing.JMenuItem();
        stud_account_menu = new javax.swing.JMenu();
        stud_settMenu = new javax.swing.JMenuItem();
        stud_addSubjMenu = new javax.swing.JMenuItem();
        stud_signoutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        stud_welcomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        stud_welcomeLabel.setText("Welcome,");

        stud_todayLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stud_todayLabel.setText("Today is,");

        subj_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        subj_label.setText("Subjects");

        stud_subName2.setText("Subject Name");

        stud_profName2.setText("Professor Name");

        stud_subEnter2.setText("Enter");
        stud_subEnter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_subEnter2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stud_subPanel2Layout = new javax.swing.GroupLayout(stud_subPanel2);
        stud_subPanel2.setLayout(stud_subPanel2Layout);
        stud_subPanel2Layout.setHorizontalGroup(
            stud_subPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stud_subPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stud_subName2)
                    .addComponent(stud_profName2))
                .addContainerGap(219, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stud_subPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stud_subEnter2)
                .addGap(103, 103, 103))
        );
        stud_subPanel2Layout.setVerticalGroup(
            stud_subPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stud_subName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stud_profName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(stud_subEnter2)
                .addContainerGap())
        );

        stud_subName.setText("Subject Name");

        stud_profName.setText("Professor Name");

        stud_subEnter.setText("Enter");
        stud_subEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_subEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stud_subPanelLayout = new javax.swing.GroupLayout(stud_subPanel);
        stud_subPanel.setLayout(stud_subPanelLayout);
        stud_subPanelLayout.setHorizontalGroup(
            stud_subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(stud_subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stud_profName)
                    .addComponent(stud_subName))
                .addContainerGap(229, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stud_subPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stud_subEnter)
                .addGap(126, 126, 126))
        );
        stud_subPanelLayout.setVerticalGroup(
            stud_subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stud_subName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stud_profName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stud_subEnter)
                .addContainerGap())
        );

        stud_subName3.setText("Subject Name");

        stud_profName3.setText("Professor Name");

        stud_subEnter3.setText("Enter");
        stud_subEnter3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_subEnter3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stud_subPanel3Layout = new javax.swing.GroupLayout(stud_subPanel3);
        stud_subPanel3.setLayout(stud_subPanel3Layout);
        stud_subPanel3Layout.setHorizontalGroup(
            stud_subPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stud_subPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stud_subName3)
                    .addComponent(stud_profName3))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stud_subPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stud_subEnter3)
                .addGap(116, 116, 116))
        );
        stud_subPanel3Layout.setVerticalGroup(
            stud_subPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stud_subName3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stud_profName3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stud_subEnter3)
                .addContainerGap())
        );

        stud_subName4.setText("Subject Name");

        stud_profName4.setText("Professor Name");

        stud_subEnter4.setText("Enter");
        stud_subEnter4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_subEnter4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stud_subPanel4Layout = new javax.swing.GroupLayout(stud_subPanel4);
        stud_subPanel4.setLayout(stud_subPanel4Layout);
        stud_subPanel4Layout.setHorizontalGroup(
            stud_subPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stud_subPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stud_subName4)
                    .addComponent(stud_profName4))
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stud_subPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stud_subEnter4)
                .addGap(124, 124, 124))
        );
        stud_subPanel4Layout.setVerticalGroup(
            stud_subPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stud_subName4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stud_profName4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(stud_subEnter4)
                .addContainerGap())
        );

        stud_subName5.setText("Subject Name");

        stud_profName5.setText("Professor Name");

        stud_subEnter5.setText("Enter");
        stud_subEnter5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_subEnter5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stud_subPanel5Layout = new javax.swing.GroupLayout(stud_subPanel5);
        stud_subPanel5.setLayout(stud_subPanel5Layout);
        stud_subPanel5Layout.setHorizontalGroup(
            stud_subPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stud_subPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stud_subName5)
                    .addComponent(stud_profName5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stud_subPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stud_subEnter5)
                .addGap(99, 99, 99))
        );
        stud_subPanel5Layout.setVerticalGroup(
            stud_subPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel5Layout.createSequentialGroup()
                .addComponent(stud_subName5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stud_profName5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stud_subEnter5)
                .addContainerGap())
        );

        stud_subName6.setText("Subject Name");

        stud_profName6.setText("Professor Name");

        stud_subEnter6.setText("Enter");
        stud_subEnter6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_subEnter6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stud_subPanel6Layout = new javax.swing.GroupLayout(stud_subPanel6);
        stud_subPanel6.setLayout(stud_subPanel6Layout);
        stud_subPanel6Layout.setHorizontalGroup(
            stud_subPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stud_subPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stud_subName6)
                    .addComponent(stud_profName6))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stud_subPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stud_subEnter6)
                .addGap(111, 111, 111))
        );
        stud_subPanel6Layout.setVerticalGroup(
            stud_subPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel6Layout.createSequentialGroup()
                .addComponent(stud_subName6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stud_profName6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stud_subEnter6)
                .addContainerGap())
        );

        stud_fname.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        stud_fname.setText("<first name>!");

        stud_date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stud_date.setText(" <month> <day>, <year>");

        stud_subName7.setText("Subject Name");

        stud_profName7.setText("Professor Name");

        stud_subEnter7.setText("Enter");
        stud_subEnter7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_subEnter7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stud_subPanel7Layout = new javax.swing.GroupLayout(stud_subPanel7);
        stud_subPanel7.setLayout(stud_subPanel7Layout);
        stud_subPanel7Layout.setHorizontalGroup(
            stud_subPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stud_subPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stud_subName7)
                    .addComponent(stud_profName7))
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stud_subPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stud_subEnter7)
                .addGap(123, 123, 123))
        );
        stud_subPanel7Layout.setVerticalGroup(
            stud_subPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stud_subName7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stud_profName7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stud_subEnter7)
                .addContainerGap())
        );

        stud_subName8.setText("Subject Name");

        stud_profName8.setText("Professor Name");

        stud_subEnter8.setText("Enter");
        stud_subEnter8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_subEnter8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stud_subPanel8Layout = new javax.swing.GroupLayout(stud_subPanel8);
        stud_subPanel8.setLayout(stud_subPanel8Layout);
        stud_subPanel8Layout.setHorizontalGroup(
            stud_subPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stud_subPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stud_subName8)
                    .addComponent(stud_profName8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stud_subPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stud_subEnter8)
                .addGap(100, 100, 100))
        );
        stud_subPanel8Layout.setVerticalGroup(
            stud_subPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stud_subName8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stud_profName8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(stud_subEnter8)
                .addContainerGap())
        );

        stud_subName10.setText("Subject Name");

        stud_profName10.setText("Professor Name");

        stud_subEnter10.setText("Enter");
        stud_subEnter10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_subEnter10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stud_subPanel10Layout = new javax.swing.GroupLayout(stud_subPanel10);
        stud_subPanel10.setLayout(stud_subPanel10Layout);
        stud_subPanel10Layout.setHorizontalGroup(
            stud_subPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stud_subPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stud_subName10)
                    .addComponent(stud_profName10))
                .addContainerGap(218, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stud_subPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stud_subEnter10)
                .addGap(111, 111, 111))
        );
        stud_subPanel10Layout.setVerticalGroup(
            stud_subPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stud_subName10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stud_profName10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stud_subEnter10)
                .addContainerGap())
        );

        stud_subName11.setText("Subject Name");

        stud_profName11.setText("Professor Name");

        stud_subEnter11.setText("Enter");
        stud_subEnter11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_subEnter11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stud_subPanel11Layout = new javax.swing.GroupLayout(stud_subPanel11);
        stud_subPanel11.setLayout(stud_subPanel11Layout);
        stud_subPanel11Layout.setHorizontalGroup(
            stud_subPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stud_subPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stud_subName11)
                    .addComponent(stud_profName11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stud_subPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stud_subEnter11)
                .addGap(98, 98, 98))
        );
        stud_subPanel11Layout.setVerticalGroup(
            stud_subPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stud_subPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stud_subName11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stud_profName11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(stud_subEnter11)
                .addContainerGap())
        );

        stud_file_menu.setText("File");

        stud_versMenu.setText("Version");
        stud_versMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_versMenuActionPerformed(evt);
            }
        });
        stud_file_menu.add(stud_versMenu);

        stud_exitMenu.setText("Exit");
        stud_exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_exitMenuActionPerformed(evt);
            }
        });
        stud_file_menu.add(stud_exitMenu);

        jMenuBar1.add(stud_file_menu);

        stud_account_menu.setText("Account");

        stud_settMenu.setText("Settings");
        stud_settMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_settMenuActionPerformed(evt);
            }
        });
        stud_account_menu.add(stud_settMenu);

        stud_addSubjMenu.setText("Add Subject");
        stud_addSubjMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_addSubjMenuActionPerformed(evt);
            }
        });
        stud_account_menu.add(stud_addSubjMenu);

        stud_signoutMenu.setText("Sign Out");
        stud_signoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_signoutMenuActionPerformed(evt);
            }
        });
        stud_account_menu.add(stud_signoutMenu);

        jMenuBar1.add(stud_account_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stud_todayLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stud_date))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stud_welcomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stud_fname))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(subj_label)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stud_subPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stud_subPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stud_subPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stud_subPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stud_subPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stud_subPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stud_subPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stud_subPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stud_subPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stud_subPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stud_welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stud_fname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stud_todayLabel)
                    .addComponent(stud_date))
                .addGap(18, 18, 18)
                .addComponent(subj_label)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stud_subPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stud_subPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stud_subPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(stud_subPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stud_subPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stud_subPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stud_subPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stud_subPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stud_subPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(stud_subPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stud_versMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_versMenuActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "School Management System Version 1.0");
            
         
         
    }//GEN-LAST:event_stud_versMenuActionPerformed

    private void stud_subEnter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_subEnter2ActionPerformed
        // TODO add your handling code here:
        SubjectView subview = new SubjectView();
         subview.setLocationRelativeTo(this);
        subview.setVisible(true);
    }//GEN-LAST:event_stud_subEnter2ActionPerformed

    private void stud_subEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_subEnterActionPerformed
        // TODO add your handling code here:
         SubjectView subview = new SubjectView();
         subview.setLocationRelativeTo(this);
        subview.setVisible(true);
         
    }//GEN-LAST:event_stud_subEnterActionPerformed

    private void stud_subEnter3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_subEnter3ActionPerformed
        // TODO add your handling code here:
        SubjectView subview = new SubjectView();
         subview.setLocationRelativeTo(this);
        subview.setVisible(true);
    }//GEN-LAST:event_stud_subEnter3ActionPerformed

    private void stud_subEnter4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_subEnter4ActionPerformed
        // TODO add your handling code here:
        SubjectView subview = new SubjectView();
         subview.setLocationRelativeTo(this);
        subview.setVisible(true);
    }//GEN-LAST:event_stud_subEnter4ActionPerformed

    private void stud_subEnter5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_subEnter5ActionPerformed
        // TODO add your handling code here:
        SubjectView subview = new SubjectView();
         subview.setLocationRelativeTo(this);
        subview.setVisible(true);
    }//GEN-LAST:event_stud_subEnter5ActionPerformed

    private void stud_subEnter6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_subEnter6ActionPerformed
        // TODO add your handling code here:
        SubjectView subview = new SubjectView();
         subview.setLocationRelativeTo(this);
        subview.setVisible(true);
    }//GEN-LAST:event_stud_subEnter6ActionPerformed

    private void stud_subEnter7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_subEnter7ActionPerformed
        // TODO add your handling code here:
        SubjectView subview = new SubjectView();
         subview.setLocationRelativeTo(this);
        subview.setVisible(true);
    }//GEN-LAST:event_stud_subEnter7ActionPerformed

    private void stud_subEnter8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_subEnter8ActionPerformed
        // TODO add your handling code here:
        SubjectView subview = new SubjectView();
         subview.setLocationRelativeTo(this);
        subview.setVisible(true);
    }//GEN-LAST:event_stud_subEnter8ActionPerformed

    private void stud_subEnter10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_subEnter10ActionPerformed
        // TODO add your handling code here:
        SubjectView subview = new SubjectView();
         subview.setLocationRelativeTo(this);
        subview.setVisible(true);
    }//GEN-LAST:event_stud_subEnter10ActionPerformed

    private void stud_subEnter11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_subEnter11ActionPerformed
        // TODO add your handling code here:
        SubjectView subview = new SubjectView();
         subview.setLocationRelativeTo(this);
        subview.setVisible(true);
    }//GEN-LAST:event_stud_subEnter11ActionPerformed

    private void stud_addSubjMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_addSubjMenuActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_stud_addSubjMenuActionPerformed

    private void stud_exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_exitMenuActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_stud_exitMenuActionPerformed

    private void stud_settMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_settMenuActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Permission not allowed, please contact the administrator");
    }//GEN-LAST:event_stud_settMenuActionPerformed

    private void stud_signoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_signoutMenuActionPerformed
        // TODO add your handling code here:
        try{
            JOptionPane.showMessageDialog(null, "Successfully Logged Out!");
            dispose();
       } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
       }
    }//GEN-LAST:event_stud_signoutMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_win().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu stud_account_menu;
    private javax.swing.JMenuItem stud_addSubjMenu;
    private javax.swing.JLabel stud_date;
    private javax.swing.JMenuItem stud_exitMenu;
    private javax.swing.JMenu stud_file_menu;
    private javax.swing.JLabel stud_fname;
    private javax.swing.JLabel stud_profName;
    private javax.swing.JLabel stud_profName10;
    private javax.swing.JLabel stud_profName11;
    private javax.swing.JLabel stud_profName2;
    private javax.swing.JLabel stud_profName3;
    private javax.swing.JLabel stud_profName4;
    private javax.swing.JLabel stud_profName5;
    private javax.swing.JLabel stud_profName6;
    private javax.swing.JLabel stud_profName7;
    private javax.swing.JLabel stud_profName8;
    private javax.swing.JMenuItem stud_settMenu;
    private javax.swing.JMenuItem stud_signoutMenu;
    private javax.swing.JButton stud_subEnter;
    private javax.swing.JButton stud_subEnter10;
    private javax.swing.JButton stud_subEnter11;
    private javax.swing.JButton stud_subEnter2;
    private javax.swing.JButton stud_subEnter3;
    private javax.swing.JButton stud_subEnter4;
    private javax.swing.JButton stud_subEnter5;
    private javax.swing.JButton stud_subEnter6;
    private javax.swing.JButton stud_subEnter7;
    private javax.swing.JButton stud_subEnter8;
    private javax.swing.JLabel stud_subName;
    private javax.swing.JLabel stud_subName10;
    private javax.swing.JLabel stud_subName11;
    private javax.swing.JLabel stud_subName2;
    private javax.swing.JLabel stud_subName3;
    private javax.swing.JLabel stud_subName4;
    private javax.swing.JLabel stud_subName5;
    private javax.swing.JLabel stud_subName6;
    private javax.swing.JLabel stud_subName7;
    private javax.swing.JLabel stud_subName8;
    private javax.swing.JPanel stud_subPanel;
    private javax.swing.JPanel stud_subPanel10;
    private javax.swing.JPanel stud_subPanel11;
    private javax.swing.JPanel stud_subPanel2;
    private javax.swing.JPanel stud_subPanel3;
    private javax.swing.JPanel stud_subPanel4;
    private javax.swing.JPanel stud_subPanel5;
    private javax.swing.JPanel stud_subPanel6;
    private javax.swing.JPanel stud_subPanel7;
    private javax.swing.JPanel stud_subPanel8;
    private javax.swing.JLabel stud_todayLabel;
    private javax.swing.JMenuItem stud_versMenu;
    private javax.swing.JLabel stud_welcomeLabel;
    private javax.swing.JLabel subj_label;
    // End of variables declaration//GEN-END:variables
}
