/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystem.student_gui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import schoolmanagementsystem.Student;
import schoolmanagementsystem.Subject;
import schoolmanagementsystem.subject_gui.AddSubjectStudentSearch;

/**
 *
 * @author japz3
 */
public class StudentDashboard extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    Student currentStudent;

    /**
     * Creates new form student
     */
    public StudentDashboard(Student student) {
        initComponents();

        this.currentStudent = student;
        this.tableModel = (DefaultTableModel) this.subjectTable.getModel();

        if (student.name.length() >= 8) {
            this.studentNameLabel.setText(student.name.substring(0, 8));
        } else {
            this.studentNameLabel.setText(student.name);
        }

        Calendar cal = Calendar.getInstance();
        this.currentDate.setText(new SimpleDateFormat("MMM dd, YYYY").format(cal.getTime()));

        StudentDashboard dash = this;
        
        subjectTable.removeColumn(subjectTable.getColumnModel().getColumn(2));
        subjectTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2 && !e.isConsumed()) {
                    e.consume();
                    SubjectInfo info = new SubjectInfo((Subject) tableModel.getValueAt(subjectTable.getSelectedRow(), 2), currentStudent);
                    info.setVisible(true);
//                    openEditor(tableModel.getValueAt(subjectTable.getSelectedRow(), 2));

                    info.addWindowListener(new WindowAdapter() {
                        @Override
                        public void windowDeactivated(WindowEvent arg0) {
                            dash.loadData();
                            // save the data
                        }
                    });
                }
            }
        });

        loadData();
    }

    void loadData() {
        try {
            tableModel.setRowCount(0);
            Subject[] subjects = this.currentStudent.getSubjects();
            for (int i = 0; i < subjects.length; i++) {
                Subject subject = subjects[i];
                Object[] field = {subject.id, subject.name, subject};
                tableModel.addRow(field);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stud_welcomeLabel = new javax.swing.JLabel();
        studentNameLabel = new javax.swing.JLabel();
        currentDate = new javax.swing.JLabel();
        stud_todayLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectTable = new javax.swing.JTable();
        refreshBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        stud_file_menu = new javax.swing.JMenu();
        stud_versMenu = new javax.swing.JMenuItem();
        stud_exitMenu = new javax.swing.JMenuItem();
        stud_account_menu = new javax.swing.JMenu();
        stud_settMenu = new javax.swing.JMenuItem();
        stud_addSubjMenu = new javax.swing.JMenuItem();
        stud_signoutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        stud_welcomeLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        stud_welcomeLabel.setText("Welcome,");

        studentNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        studentNameLabel.setText("<first name>!");

        currentDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        currentDate.setText(" <month> <day>, <year>");

        stud_todayLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stud_todayLabel.setText("Today is");

        subjectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Subject Name", "Professor", "Data"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(subjectTable);

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        stud_file_menu.setText("File");

        stud_versMenu.setText("Version");
        stud_versMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_versMenuActionPerformed(evt);
            }
        });
        stud_file_menu.add(stud_versMenu);

        stud_exitMenu.setText("Exit");
        stud_exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_exitMenuActionPerformed(evt);
            }
        });
        stud_file_menu.add(stud_exitMenu);

        jMenuBar1.add(stud_file_menu);

        stud_account_menu.setText("Account");

        stud_settMenu.setText("Settings");
        stud_settMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_settMenuActionPerformed(evt);
            }
        });
        stud_account_menu.add(stud_settMenu);

        stud_addSubjMenu.setText("Add Subject");
        stud_addSubjMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_addSubjMenuActionPerformed(evt);
            }
        });
        stud_account_menu.add(stud_addSubjMenu);

        stud_signoutMenu.setText("Sign Out");
        stud_signoutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_signoutMenuActionPerformed(evt);
            }
        });
        stud_account_menu.add(stud_signoutMenu);

        jMenuBar1.add(stud_account_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stud_todayLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentDate))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stud_welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentNameLabel))
                    .addComponent(refreshBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stud_welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stud_todayLabel)
                    .addComponent(currentDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(refreshBtn)
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stud_versMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_versMenuActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "School Management System Version 1.0");
    }//GEN-LAST:event_stud_versMenuActionPerformed

    private void stud_addSubjMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_addSubjMenuActionPerformed
        AddSubjectStudentSearch frame = new AddSubjectStudentSearch(currentStudent);
        frame.setVisible(true);
        
        StudentDashboard dash = this;
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowDeactivated(WindowEvent arg0) {
                dash.loadData();
            }
        });
    }//GEN-LAST:event_stud_addSubjMenuActionPerformed

    private void stud_exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_exitMenuActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_stud_exitMenuActionPerformed

    private void stud_settMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_settMenuActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Permission not allowed, please contact the administrator");
    }//GEN-LAST:event_stud_settMenuActionPerformed

    private void stud_signoutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_signoutMenuActionPerformed
        // TODO add your handling code here:
        try {
            JOptionPane.showMessageDialog(null, "Successfully Logged Out!");
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_stud_signoutMenuActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        this.loadData();
    }//GEN-LAST:event_refreshBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel currentDate;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JMenu stud_account_menu;
    private javax.swing.JMenuItem stud_addSubjMenu;
    private javax.swing.JMenuItem stud_exitMenu;
    private javax.swing.JMenu stud_file_menu;
    private javax.swing.JMenuItem stud_settMenu;
    private javax.swing.JMenuItem stud_signoutMenu;
    private javax.swing.JLabel stud_todayLabel;
    private javax.swing.JMenuItem stud_versMenu;
    private javax.swing.JLabel stud_welcomeLabel;
    private javax.swing.JLabel studentNameLabel;
    private javax.swing.JTable subjectTable;
    // End of variables declaration//GEN-END:variables
}
