/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystem.student_gui;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import schoolmanagementsystem.Subject;
import schoolmanagementsystem.student_gui.SubView;
import schoolmanagementsystem.student_gui.NotesView;


/**
 *
 * @author japz3
 */
public class SubjectView extends javax.swing.JFrame {
    private Subject[] subjects;
     private DefaultTableModel resultTableModel;
     SubjectView(Subject[] subjects) {
         this.initComponents();
         this.subjects = subjects;
         this.resultTableModel = (DefaultTableModel) sTable1.getModel();
     }
    public void loadSubjectsToTable() {
        resultTableModel.setRowCount(0);

        for (int i = 0; i < subjects.length; i++) {
            Subject sub = subjects[i];
	  //Professor prof = sub.getProfessor();

            Object[] fields = {
                sub.id,
	      sub.name,
	      //prof.name
            };

            resultTableModel.addRow(fields);
        }
    }

    /**
     * Creates new form SubjectView
     */
    public SubjectView() {
        initComponents();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stud_subjViewSubLabel = new javax.swing.JLabel();
        stud_subjViewProfLabel = new javax.swing.JLabel();
        stud_subViewSessButton = new javax.swing.JButton();
        stud_subViewNoteButton = new javax.swing.JButton();
        sTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        stud_subjViewSubLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        stud_subjViewSubLabel.setText("Subject Name");

        stud_subjViewProfLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stud_subjViewProfLabel.setText("Professor Name");

        stud_subViewSessButton.setText("Sessions");
        stud_subViewSessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_subViewSessButtonActionPerformed(evt);
            }
        });

        stud_subViewNoteButton.setText("Notes");
        stud_subViewNoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_subViewNoteButtonActionPerformed(evt);
            }
        });

        sTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ));
        sTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sTable1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stud_subjViewSubLabel)
                    .addComponent(stud_subjViewProfLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stud_subViewSessButton)
                        .addGap(31, 31, 31)
                        .addComponent(stud_subViewNoteButton)))
                .addContainerGap(477, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(7, Short.MAX_VALUE)
                    .addComponent(sTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(7, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stud_subjViewSubLabel)
                .addGap(18, 18, 18)
                .addComponent(stud_subjViewProfLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stud_subViewSessButton)
                    .addComponent(stud_subViewNoteButton))
                .addContainerGap(539, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(126, Short.MAX_VALUE)
                    .addComponent(sTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stud_subViewSessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_subViewSessButtonActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_stud_subViewSessButtonActionPerformed

    private void stud_subViewNoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_subViewNoteButtonActionPerformed
        // TODO add your handling code here:
        NotesView noteview = new NotesView();
        noteview.setLocationRelativeTo(this);
        noteview.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_stud_subViewNoteButtonActionPerformed

    private void sTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sTable1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_sTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable sTable1;
    private javax.swing.JButton stud_subViewNoteButton;
    private javax.swing.JButton stud_subViewSessButton;
    private javax.swing.JLabel stud_subjViewProfLabel;
    private javax.swing.JLabel stud_subjViewSubLabel;
    // End of variables declaration//GEN-END:variables
}
