/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystem.student_gui;
import schoolmanagementsystem.student_gui.SubView;
import schoolmanagementsystem.student_gui.NotesView;


/**
 *
 * @author japz3
 */
public class SubjectView extends javax.swing.JFrame {

    /**
     * Creates new form SubjectView
     */
    public SubjectView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stud_subjViewSubLabel = new javax.swing.JLabel();
        stud_subjViewProfLabel = new javax.swing.JLabel();
        stud_subViewSessButton = new javax.swing.JButton();
        stud_subViewNoteButton = new javax.swing.JButton();
        sScrollPane1 = new javax.swing.JScrollPane();
        sTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        stud_subjViewSubLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        stud_subjViewSubLabel.setText("Subject Name");

        stud_subjViewProfLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stud_subjViewProfLabel.setText("Professor Name");

        stud_subViewSessButton.setText("Sessions");
        stud_subViewSessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_subViewSessButtonActionPerformed(evt);
            }
        });

        stud_subViewNoteButton.setText("Notes");
        stud_subViewNoteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stud_subViewNoteButtonActionPerformed(evt);
            }
        });

        sTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ));
        sScrollPane1.setViewportView(sTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 648, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stud_subjViewSubLabel)
                            .addComponent(stud_subjViewProfLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stud_subViewSessButton)
                                .addGap(31, 31, 31)
                                .addComponent(stud_subViewNoteButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stud_subjViewSubLabel)
                .addGap(18, 18, 18)
                .addComponent(stud_subjViewProfLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stud_subViewSessButton)
                    .addComponent(stud_subViewNoteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stud_subViewSessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_subViewSessButtonActionPerformed
        // TODO add your handling code here:
       SubView subv = new SubView();
         subv.setLocationRelativeTo(this);
        subv.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_stud_subViewSessButtonActionPerformed

    private void stud_subViewNoteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stud_subViewNoteButtonActionPerformed
        // TODO add your handling code here:
        NotesView noteview = new NotesView();
        noteview.setLocationRelativeTo(this);
        noteview.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_stud_subViewNoteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane sScrollPane1;
    private javax.swing.JTable sTable1;
    private javax.swing.JButton stud_subViewNoteButton;
    private javax.swing.JButton stud_subViewSessButton;
    private javax.swing.JLabel stud_subjViewProfLabel;
    private javax.swing.JLabel stud_subjViewSubLabel;
    // End of variables declaration//GEN-END:variables
}
